// <auto-generated />
using System;
using ByblosMiPH.API.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ByblosMiPH.API.Migrations
{
    [DbContext(typeof(MiPruebaDbContext))]
    [Migration("20200719155739_LaPrimera")]
    partial class LaPrimera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ByblosMiPH.API.Domain.Models.Banco", b =>
                {
                    b.Property<int>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Código")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualización")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("BancoId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Bancos");

                    b.HasData(
                        new
                        {
                            BancoId = 1,
                            Código = "BG",
                            EstadoId = 1,
                            FechaActualización = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(7298),
                            FechaCreación = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(7290),
                            Nombre = "Banco General"
                        },
                        new
                        {
                            BancoId = 2,
                            Código = "BNP",
                            EstadoId = 1,
                            FechaActualización = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(8017),
                            FechaCreación = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(8013),
                            Nombre = "Banco Nacional de Panamá"
                        },
                        new
                        {
                            BancoId = 3,
                            Código = "CA",
                            EstadoId = 1,
                            FechaActualización = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(8031),
                            FechaCreación = new DateTime(2020, 7, 19, 10, 57, 39, 681, DateTimeKind.Local).AddTicks(8031),
                            Nombre = "Caja de Ahorros"
                        });
                });

            modelBuilder.Entity("ByblosMiPH.API.Domain.Models.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Código")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime>("FechaActualización")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("EstadoId");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            EstadoId = -1,
                            Código = "INAC",
                            FechaActualización = new DateTime(2020, 7, 19, 10, 57, 39, 680, DateTimeKind.Local).AddTicks(5692),
                            FechaCreación = new DateTime(2020, 7, 19, 10, 57, 39, 680, DateTimeKind.Local).AddTicks(5432),
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            EstadoId = 1,
                            Código = "ACTI",
                            FechaActualización = new DateTime(2020, 7, 19, 10, 57, 39, 680, DateTimeKind.Local).AddTicks(5951),
                            FechaCreación = new DateTime(2020, 7, 19, 10, 57, 39, 680, DateTimeKind.Local).AddTicks(5942),
                            Nombre = "Activo"
                        });
                });

            modelBuilder.Entity("ByblosMiPH.API.Domain.Models.Banco", b =>
                {
                    b.HasOne("ByblosMiPH.API.Domain.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
